# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('lattitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('altitude', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
