# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='altitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='lattitude',
            new_name='lng',
        ),
    ]
